echo " "
neofetch

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


export ZSH="$HOME/.oh-my-zsh"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(sudo git zsh-autosuggestions zsh-syntax-highlighting golang rust brew)

ZSH_THEME="powerlevel10k/powerlevel10k"

source $ZSH/oh-my-zsh.sh

alias zshconfig="lvim ~/.config/zsh/zshrc"
alias kittyconfig="lvim ~/.config/kitty/kitty.conf"
alias p10kconfig="lvim ~/.p10k.zsh"
alias neofetchconfig="lvim ~/.config/neofetch/config.conf"
alias lvimconfig="lvim ~/.config/lvim/config.lua"
alias dotfiles="lvim ~/.config"
alias ohmyzsh="nano ~/.oh-my-zsh"
alias m="mise"
alias ml="mise list"
alias mu="mise use -g"
alias vs="code ."
alias cdc="cd ~/Code && ls"
alias cdo="cd ~/Others && ls"
alias cdv="cd ~/Vert/ && ls"
alias cdco="cd ~/.config/ && ls"
alias byebye="shutdown now"
alias c="clear && echo"
alias dev="npm run dev"
alias prettier="npx prettier . --write"
alias mkvenv="python3 -m venv venv"
alias venvon="source venv/bin/activate"
alias venvoff="deactivate"
alias delete="rm -rf"
alias sdelete="sudo rm -rf"
alias dcu="docker compose up"
alias dcd="docker compose down"
alias ros="source ~/ros2_rolling/install/local_setup.zsh"
alias sis="source install/setup.zsh"
alias flushdns="sudo resolvectl flush-caches"
alias zshrc="source ~/.zshrc"
alias pull="git pull"
alias n="npm run"
alias kb="kubectl"
alias asdfg="asdf global"
alias asdfi="asdf install"
alias ls="eza --header --icons --sort=type"
dockerrmc() {
  docker rm $(docker ps -qa) -vf
}

dockerrmi() {
  docker image rm $(docker image ls -aq) -f
}

dockerrmv() {
  docker volume rm $(docker volume ls -q)
}

dockersta() {
  docker stop $(docker ps -aq)
}

export PATH=/Users/paulo/.local/bin:$PATH
export HOMEBREW_NO_ENV_HINTS="true"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
if command -v zoxide > /dev/null; then
  eval "$(zoxide init zsh)"
fi


export PATH="$PATH:/Users/paulo/.risc0/bin"
